name: 'GSA/grace-config-differ'
description: 'Lambda function to email a report of configuration changes detected by AWS Config Service'
license: cc0-1.0
openSourceProject: 1
governmentWideReuseProject: 1
tags:
    - open-source
    - opensource
    - grace
    - devsecops
contact:
    email: devsecops-core@gsa.gov
